name: Valentine Bot ðŸ’–

on:
  schedule:
    # 00:00 IST = 18:30 UTC
    - cron: "30 13 * * *"
    # 09:00 IST = 03:30 UTC
    - cron: "30 03 * * *"
  workflow_dispatch:
    inputs:
      mode:
        description: 'Select mode: unlock or reminder'
        required: true
        default: 'unlock'
        type: choice
        options:
        - unlock
        - reminder

jobs:
  unlock-bot:
    runs-on: ubuntu-latest
    if: github.event.schedule == '30 16 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'unlock')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram Bot (Unlock)
        run: python telegram/bot.py unlock

  reminder-bot:
    runs-on: ubuntu-latest
    if: github.event.schedule == '40 16 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.mode == 'reminder')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram Bot (Reminder)
        run: python telegram/bot.py reminder
